<?php
/**
 * @author Bloomreach
 * @copyright Copyright (c) Bloomreach (https://www.bloomreach.com/)
 */

// phpcs:disable Generic.Files.LineLength.TooLong
use Bloomreach\EngagementConnector\Block\Tracking\Event;
use Bloomreach\EngagementConnector\ViewModel\Tracking\Config as ConfigViewModel;

/** @var Event $block */
/** @var ConfigViewModel $configViewModel */
$configViewModel = $block->getData('config_view_model');
?>
<?php if ($configViewModel): ?>
    <script>
        require([
            'Bloomreach_EngagementConnector/js/tracking/event-sender'
        ], function(eventSender) {
            'use strict';
            var trackingProvider = "<?= $block->escapeHtml($configViewModel->getTrackingProvider()); ?>";
            var eventList = <?= $block->getJsLayout(); ?>;
            eventSender.sendListOfEvents(eventList, trackingProvider);
        });
    </script>
    <?= $block->getChildHtml(); ?>
<?php endif; ?>
