<?php
/**
 * @author Bloomreach
 * @copyright Copyright (c) Bloomreach (https://www.bloomreach.com/)
 */
// phpcs:ignoreFile
use Bloomreach\EngagementConnector\Block\Tracking\Event;
use Bloomreach\EngagementConnector\ViewModel\Tracking\Config as ConfigViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Event $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var ConfigViewModel $configViewModel */
$configViewModel = $block->getData('config_view_model');
?>
<?php if ($configViewModel): ?>
    <?php
    $scriptString = <<<script
    require([
        'Bloomreach_EngagementConnector/js/tracking/event-sender'
    ], function(eventSender) {
        'use strict';
        var trackingProvider = "{$escaper->escapeHtml($configViewModel->getTrackingProvider())}";
        var eventList = {$block->getJsLayout()};
        eventSender.sendListOfEvents(eventList, trackingProvider);
    });
    script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
    <?= $block->getChildHtml(); ?>
<?php endif; ?>
