<?php
/**
 * @author Bloomreach
 * @copyright Copyright (c) Bloomreach (https://www.bloomreach.com/)
 */

use Bloomreach\EngagementConnector\Block\Adminhtml\System\Config\Button;
use Magento\Framework\Escaper;

/** @var Button $block */
/** @var Escaper $escaper */
$isInProgress = $block->getIsImportInProgress();
$isEnabled = $block->getIsEnabled() && !$isInProgress;
$messageContainer = $escaper->escapeHtmlAttr($block->getHtmlId() . '_message');
?>
<div class="actions">
    <div class="<?= /* @noEscape */ $messageContainer; ?>">
        <?php if ($isInProgress):?>
        <div class="messages">
            <div class="message message-progress">
                <strong><?= $escaper->escapeHtml(__('Disabled.')) ?></strong>
                <?= $escaper->escapeHtml(
                    __('Run initial imports is currently disabled, because there are imports already in progress.')
                ); ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
    <button type="button" id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()); ?>"
        <?= !$isEnabled ? 'disabled' : ''; ?>>
        <span><?= $escaper->escapeHtml($block->getButtonLabel()); ?></span>
    </button>
</div>
<script type="text/x-magento-init">
    {
        "#<?= $escaper->escapeHtml($block->getHtmlId()) ?>": {
            "Bloomreach_EngagementConnector/js/system/config/button/send-ajax-request": {
                "ajaxUrl": "<?= $escaper->escapeUrl($block->getButtonUrl()); ?>",
                "isEnabled": "<?= /* @noEscape */ $isEnabled; ?>",
                "buttonId": "#<?= $escaper->escapeHtml($block->getHtmlId()); ?>",
                "messageContainer": ".<?= /* @noEscape */ $messageContainer; ?>",
                "requiredFieldsSelectors": "<?= /* @noEscape */ $block->getRequiredFieldsSelectors(); ?>",
                "disableButtonAfterClick": "<?= /* @noEscape */ $block->getDisableButtonAfterClick(); ?>"
            }
        }
    }
</script>
